import { NextRequest } from "next/server";
import { spawn, exec } from "node:child_process";
import { existsSync, writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

// ── Types ────────────────────────────────────────────────────

interface LoopEvent {
  type: "progress" | "phase" | "done" | "error";
  phase?: string;
  turn?: number;
  maxTurns?: number;
  status?: "running" | "pass" | "fail";
  message?: string;
  report?: LoopReport;
}

interface LoopReport {
  goal: string;
  strategy: string;
  turns: number;
  elapsedMs: number;
  verifyCommand: string;
  log: string;
}

// ── Helpers ──────────────────────────────────────────────────

function findPiBinary(): string {
  // Check common paths
  const paths = [
    "/opt/homebrew/bin/pi",
    "/usr/local/bin/pi",
    join(process.env.HOME || "/tmp", ".local/bin/pi"),
  ];
  for (const p of paths) {
    if (existsSync(p)) return p;
  }
  return "pi"; // fallback to PATH
}

function autoGenerateVerify(cwd: string): string | null {
  if (existsSync(join(cwd, "package.json"))) {
    try {
      const pkg = JSON.parse(readFileSync(join(cwd, "package.json"), "utf-8"));
      if (pkg.scripts?.typecheck) {
        const content = `#!/bin/bash\n# Auto-generated by pi++ loop\nnpm run typecheck\n`;
        mkdirSync(join(cwd, ".pi"), { recursive: true });
        writeFileSync(join(cwd, ".pi/verify.sh"), content, { mode: 0o755 });
        return "bash .pi/verify.sh";
      }
      if (pkg.scripts?.build) {
        const content = `#!/bin/bash\n# Auto-generated by pi++ loop\nnpm run build\n`;
        mkdirSync(join(cwd, ".pi"), { recursive: true });
        writeFileSync(join(cwd, ".pi/verify.sh"), content, { mode: 0o755 });
        return "bash .pi/verify.sh";
      }
    } catch { /* ignore */ }
  }
  return null;
}

function discoverVerify(cwd: string): string {
  // 1. Check .pi/verify.sh
  if (existsSync(join(cwd, ".pi/verify.sh"))) {
    return "bash .pi/verify.sh";
  }
  // 2. Auto-generate from package.json
  const auto = autoGenerateVerify(cwd);
  if (auto) return auto;
  // 3. Fallback
  if (existsSync(join(cwd, "package.json"))) return "npm run build";
  if (existsSync(join(cwd, "go.mod"))) return "go build ./...";
  if (existsSync(join(cwd, "Cargo.toml"))) return "cargo build";
  return "npm run build"; // last resort
}

async function runCommand(cmd: string, cwd: string): Promise<{ code: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    exec(cmd, { cwd, maxBuffer: 10 * 1024 * 1024 }, (error, stdout, stderr) => {
      resolve({ code: error?.code ?? 0, stdout, stderr });
    });
  });
}

async function runPi(prompt: string, cwd: string, resume: boolean, model?: string): Promise<string> {
  const piBin = findPiBinary();
  const args = ["-p", prompt, "--mode", "json"];
  if (resume) args.push("--continue");
  if (model) args.push("--model", model);

  return new Promise((resolve) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const child = spawn(piBin, args, {
      cwd,
      env: { ...process.env, PATH: `${process.env.HOME || ""}/.local/bin:/opt/homebrew/bin:${process.env.PATH || ""}` },
      stdio: ["pipe", "pipe", "pipe"],
    }) as any;
    child.stdin?.end();

    let output = "";
    child.stdout?.on("data", (d: Buffer) => { output += d.toString(); });
    child.stderr?.on("data", () => { /* ignore stderr */ });

    child.on("close", () => resolve(output));
  });
}

function isAbortLikeError(error: unknown): boolean {
  if (!(error instanceof Error)) return false;
  return error.name === "AbortError" || error.name === "ResponseAborted";
}

// ── Route ────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  let body: { goal?: string; workspace?: string; makerModel?: string; checkerModel?: string };
  try { body = await req.json(); } catch {
    return Response.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const goal = body.goal;
  const cwd = body.workspace || process.cwd();
  const makerModel = body.makerModel;
  const checkerModel = body.checkerModel;

  if (!goal) {
    return Response.json({ error: "goal is required" }, { status: 400 });
  }

  const verify = discoverVerify(cwd);
  const maxTurns = 6;
  const level1Turns = 3;
  const level2Turns = 3;
  const startTime = Date.now();
  let fullLog = "";

  const encoder = new TextEncoder();
  const { readable, writable } = new TransformStream();
  const writer = writable.getWriter();

  const send = async (event: LoopEvent) => {
    if (req.signal.aborted) return false;
    try {
      await writer.write(encoder.encode(`data: ${JSON.stringify(event)}\n\n`));
      return true;
    } catch (e) {
      if (isAbortLikeError(e)) return false;
      throw e;
    }
  };

  (async () => {
    try {
      // ── Phase 1: Direct fix ────────────────────────────────
      await send({ type: "phase", phase: "Phase 1: 直接修复", turn: 0, maxTurns: level1Turns, status: "running" });

      let currentTask = goal;

      for (let turn = 1; turn <= level1Turns && turn <= maxTurns; turn++) {
        await send({ type: "progress", phase: "Phase 1", turn, maxTurns: level1Turns, status: "running" });

        const piOutput = await runPi(
          turn === 1
            ? `${goal}。改动要最小化。完成后运行 ${verify} 确认。`
            : `验证失败。请读取错误信息，只修改必要的文件来修复问题。完成后运行 ${verify} 确认。`,
          cwd,
          turn > 1,
          makerModel,
        );
        fullLog += `\n--- Turn ${turn} (Phase 1) ---\n${piOutput.slice(-500)}\n`;

        const verifyResult = await runCommand(verify, cwd);
        fullLog += `\nVerify: ${verifyResult.code === 0 ? "PASS" : "FAIL"}\n${verifyResult.stdout.slice(-300)}${verifyResult.stderr.slice(-300)}\n`;

        if (verifyResult.code === 0) {
          await send({ type: "progress", phase: "Phase 1", turn, maxTurns: level1Turns, status: "pass" });
          const elapsed = Date.now() - startTime;
          const report: LoopReport = {
            goal,
            strategy: "Phase 1 直接修复",
            turns: turn,
            elapsedMs: elapsed,
            verifyCommand: verify,
            log: fullLog,
          };
          await send({ type: "done", report });
          return;
        }

        await send({ type: "progress", phase: "Phase 1", turn, maxTurns: level1Turns, status: "fail" });
        currentTask = "上次修复未通过验证。请重新读取错误信息，用不同的方法修复。";
      }

      // ── Phase 2: Maker + Checker ────────────────────────────
      const remaining = maxTurns - level1Turns;
      if (remaining <= 0) {
        await send({
          type: "done",
          report: { goal, strategy: "未能修复", turns: level1Turns, elapsedMs: Date.now() - startTime, verifyCommand: verify, log: fullLog },
        });
        return;
      }

      await send({ type: "phase", phase: "Phase 2: Maker + Checker", turn: 0, maxTurns: remaining, status: "running" });

      for (let turn = 1; turn <= remaining; turn++) {
        const globalTurn = level1Turns + turn;

        // Maker
        await send({ type: "progress", phase: "Maker", turn: globalTurn, maxTurns, status: "running", message: "编写代码..." });
        const makerOutput = await runPi(
          `你是代码编写者。任务：${currentTask}。改动要最小化。完成后运行 ${verify} 确认。`,
          cwd,
          true,
          makerModel,
        );
        fullLog += `\n--- Turn ${globalTurn} Maker ---\n${makerOutput.slice(-500)}\n`;

        const verifyResult = await runCommand(verify, cwd);
        if (verifyResult.code !== 0) {
          await send({ type: "progress", phase: "Maker", turn: globalTurn, maxTurns, status: "fail", message: "验证未通过" });
          fullLog += `\nVerify: FAIL\n${verifyResult.stdout.slice(-300)}\n`;
          currentTask = "上次修复未通过验证。请重新修复。";
          continue;
        }

        // Checker
        await send({ type: "progress", phase: "Checker", turn: globalTurn, maxTurns, status: "running", message: "审核中..." });
        const reviewOutput = await runPi(
          `你是代码审核者。用 git diff 审查所有改动。
标准：改动是否最小化？是否有逻辑错误？类型是否安全？是否符合现有风格？
只回答 PASS 或 FAIL，并给出简要理由。`,
          cwd,
          false,
          checkerModel,
        );
        fullLog += `\n--- Turn ${globalTurn} Checker ---\n${reviewOutput.slice(-500)}\n`;

        if (reviewOutput.toUpperCase().includes("PASS")) {
          await send({ type: "progress", phase: "Checker", turn: globalTurn, maxTurns, status: "pass", message: "审核通过" });
          const elapsed = Date.now() - startTime;
          const report: LoopReport = {
            goal,
            strategy: "Phase 2 Maker+Checker",
            turns: globalTurn,
            elapsedMs: elapsed,
            verifyCommand: verify,
            log: fullLog,
          };
          await send({ type: "done", report });
          return;
        }

        await send({ type: "progress", phase: "Checker", turn: globalTurn, maxTurns, status: "fail", message: "审核未通过" });
        currentTask = `上次改动被审核拒绝。审核意见：${reviewOutput.slice(-300)}。请根据反馈重新修改代码，然后运行 ${verify} 确认。`;
      }

      // Failed
      await send({
        type: "done",
        report: { goal, strategy: "未能自动修复", turns: maxTurns, elapsedMs: Date.now() - startTime, verifyCommand: verify, log: fullLog },
      });
    } catch (e) {
      if (!req.signal.aborted) {
        await send({ type: "error", message: e instanceof Error ? e.message : "Unknown error" });
      }
    } finally {
      try { await writer.close(); } catch { /* closed */ }
    }
  })();

  return new Response(readable, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
}
